version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=redash
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=redash
    volumes:
      - ${POSTGRES_DATADIR}:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ${REDIS_DATADIR}:/data

  redash:
    image: redash/redash:latest
    container_name: redash
    depends_on:
      - postgres
      - redis
    environment:
      - REDASH_DATABASE_URL=postgresql://redash:password@postgres:5432/redash
      - REDASH_REDIS_URL=redis://redis:6379/0
    ports:
      - "5000:5000"